### ISSUE TITLE
[backup-appdata.sh] 'rev' is not available on syno

### ISSUE THREAD

**Issue by mvanbaak** [Drazzilb08/userScripts#19]
search and replace `cut -c 2- | rev | cut -c 2- | rev` with `sed -e 's/^"//' -e 's/"$//'` and the script no longer depends on `rev` which is not available on eg synology

**Comment by Drazzilb08** [comment]
Closed with dev commit [ac09d66](https://github.com/Drazzilb08/userScripts/commit/ac09d66b32df0efc532bab820886585fd89de9f3)

Thank you for the original PR @mvanbaak
