### ISSUE TITLE
[backup-appdata.sh] unraid_notify or notify

### ISSUE THREAD

**Issue by TRaSH-** [Drazzilb08/userScripts#2]
If you set `unraid_notify=yes` it gives the following error

```
/tmp/user.scripts/tmpScripts/3.Backup-Appdata Drazzilb/script: line 525: /usr/local/emhttp/plugins/dynamix/scripts/unraid_notify: No such file or directory

Discord error notification sent.
{"embeds": ["0"]}
Discord notification sent.
```

in my case i don't have unraid_notify but i do have notify in that location

**Comment by Drazzilb08** [comment]
This error should be fixed with commit [bc4badb](https://github.com/Drazzilb08/userScripts/commit/bc4badbac9ca1331bed6a0acb12cdccfdae70730)
