### ISSUE TITLE
Option to use multiple status in upgradinatorr

### ISSUE THREAD

**Issue by BaukeZwart** [Drazzilb08/userScripts#58]
I would like upgradinatorr to check multiple status for upgrades.
For example, in Sonarr I would like it to check both "continuing" and "ended" ( not much point in checking upcoming)
Would it be possible to add more than one status to be checked?

**Comment by Drazzilb08** [comment]
When I get a chance to I'll take a look at implementing this. No idea when I'll have time to do so.

**Comment by Drazzilb08** [comment]
@BaukeZwart 
Sent a DM on Discord with a test subject

**Comment by Drazzilb08** [comment]
closed with 9499b62
