### ISSUE TITLE
Appdata backup script clarification

### ISSUE THREAD

**Issue by PierreDurrr** [Drazzilb08/userScripts#60]
Got the appdata backup script working few days ago, but don't know if i use it wrong, if i've misunderstood or if it's a bug.

Got a docker-compose.yml file per service, stored alongside the corresponding /config folder.
When running the script, only /config folder is backed up, compose file is not included.

Is that intended ?

**Comment by Drazzilb08** [comment]
All files within the config folder should be backed up. This information is gathered from docker. If you store your compose in a different dir the. You'll need something like folder backup to backup that specific folder.

**Comment by Drazzilb08** [comment]
Closing issue.
