### ISSUE TITLE
script FR: to remove obsolete files and folders from the assets dir when movie/series are removed from Plex

### ISSUE THREAD

**Issue by BaukeZwart** [Drazzilb08/userScripts#62]
https://discord.com/channels/492590071455940612/1124032073557086258/1169998115395350588

**Comment by Drazzilb08** [comment]
I'll see what I can cook up for this. I already have an idea of how to do it effectively. Just need time to write it.

**Comment by Drazzilb08** [comment]
request filled with [086992d](https://github.com/Drazzilb08/userScripts/commit/086992dd92dd1e4c0739d10290085cbf362c7259)
