### ISSUE TITLE
renamer doesn't recognize a non-English original title

### ISSUE THREAD

**Issue by BaukeZwart** [Drazzilb08/userScripts#70]
https://discord.com/channels/492590071455940612/1174915855847534652/1182352064236486686

**Comment by Drazzilb08** [comment]
Fix for this will be to instead of overwriting the arr_title with the "original title" to instead also to match by original title as an `or` statement.

When I get a chance, I'll push this out (hopfully soon)

**Comment by Drazzilb08** [comment]
Closed with commit: [13030dd](https://github.com/Drazzilb08/userScripts/commit/13030dd275b9c37cc1cab35d2434f74b668d9ae7)

also @garypiner I commented on your PR. Thank you very much for that. Please let me know if I missed something with my recent commit.

**Comment by BaukeZwart** [comment]
How can an update in renamer_cleaner fix this issue with renamer?

**Comment by Drazzilb08** [comment]
Oops was supposed to be commit b48cac9
