### ISSUE TITLE
FR - have renamer_cleanarr support multiple assets dir

### ISSUE THREAD

**Issue by BaukeZwart** [Drazzilb08/userScripts#73]
I use renamer to copy posters to an output dir and then run fix_border and have that copy the posters to the PMM assests dir.
To clean them both, I now have 2 renamer cleanarr scripts and config  entries.
It would be nice if we could combine this into one.
My current setup works, so no rush, just wanted to drop this here.

**Comment by Drazzilb08** [comment]
Thanks for the suggestion. That's a fairly easy fix. I'll put it on my todo list
