### ISSUE TITLE
Wiki link for movie deletarr gives File not found

### ISSUE THREAD

**Issue by zwimer** [Drazzilb08/userScripts#77]
Steps to reproduce:
1. Go to https://github.com/Drazzilb08/userScripts/blob/master/python-scripts/movie-deletarr.py
2. Scroll down to Movie Deletarr
3. Click the link. It will take you to: https://github.com/Drazzilb08/userScripts/blob/master/python-scripts/movie-deletarr.py

I think the issue is an underscore and a dash got swapped?

**Comment by Drazzilb08** [comment]
Ah, I see what you mean, but many changes to both the scripts and the wiki are coming soon ™️  
Thanks for looking out

**Comment by Drazzilb08** [comment]
This has been fixed, thank you.
