### ISSUE TITLE
[BUG] Date count not correct

### ISSUE THREAD

**Issue by TRaSH-** [Drazzilb08/userScripts#9]
If the last backup was on the 7th
![image](https://user-images.githubusercontent.com/6155095/184504745-53feeeb9-a718-43fd-b6bc-33a676432dfa.png)
![image](https://user-images.githubusercontent.com/6155095/184504788-e4307e3d-3226-443f-9d40-8ff34fbf290e.png)

And i set the schedule on 7 days
![image](https://user-images.githubusercontent.com/6155095/184504718-7bbd8d4d-c83c-47c0-9d49-31c1a237d61c.png)

then the next backup should be on the 14th
7+7 = 14

keep in mind of the date format used
7 = day
8 = month
last backup 7-8-2022

![image](https://user-images.githubusercontent.com/6155095/184504807-b57d556a-d408-4dad-b281-2f0ba5e4b225.png)

![image](https://user-images.githubusercontent.com/6155095/184504829-5ff8abd2-9c82-4aab-a55f-3c07119e63b0.png)

**Comment by Drazzilb08** [comment]
![image](https://user-images.githubusercontent.com/65743746/184509499-69d638a2-438c-4dec-9245-0aefa59613a0.png)
Okay think I've solved this one in v2.3.20 in commit 
This should be fixed in d8044699e96cea5a39db779e5e55f1022dcca023

Please do some more tests to see if this is resolved.
